FOR-1 & FOR-8 & FOR-10
FundacionForge/Project-Backend pull request #2
Opened 2023-07-26 19:26 UTC by JefersonPalomo

Se añadió repositorio de Alumno.
Endpoints de Teacher creados.

2023-07-26 23:10 UTC, MarcosAlanya19 commented on src/main/java/com/example/forge/models/entities/Teacher.java
> -
usar el los decoradores para tener todos los contructores y el contructor vacio

2023-07-26 23:10 UTC, MarcosAlanya19 commented on src/main/java/com/example/forge/controllers/TeacherController.java
> +    public Teacher update(@PathVariable("id") Long id, @RequestParam("name") String name,
Cambiar nombre a: updateTeacher

2023-07-26 23:10 UTC, MarcosAlanya19 commented on src/main/java/com/example/forge/models/entities/Teacher.java
> +
usar el decorador para llamar el contructor lleno y vacio

2023-07-27 00:36 UTC, MarcosAlanya19 commented on src/main/java/com/example/forge/repositorybase/RepositoryBase.java
> +	List<T> findAll();
Borrar el interior de esta interface

2023-07-27 00:36 UTC, MarcosAlanya19 commented on src/main/java/com/example/forge/repositorybase/RepositoryBase.java
> +public interface RepositoryBase<T> extends CrudRepository<T, Long> {
Cambiar de nombre a BaseRepository

2023-07-27 00:36 UTC, MarcosAlanya19 commented on src/main/java/com/example/forge/coreservice/CoreService.java
> +	private RepositoryBase<T> repositoryBase;
utilizar @Autowired

2023-07-27 00:36 UTC, MarcosAlanya19 commented on src/main/java/com/example/forge/coreservice/CoreService.java
> +public class CoreService<T> {
Cambiar nombre a BaseService

2023-07-27 00:36 UTC, MarcosAlanya19 commented on src/main/java/com/example/forge/coreservice/CoreService.java
> +	public T update(T object) {
cambiar de nombre a updateById

2023-07-27 00:36 UTC, MarcosAlanya19 commented on src/main/java/com/example/forge/coreservice/CoreService.java
> +	public T save(T object) {
cambiar de nombre a create

2023-07-27 00:41 UTC, MarcosAlanya19 commented on src/main/java/com/example/forge/coreservice/CoreService.java
> +	private RepositoryBase<T> repositoryBase;
cambiar de nombre a private BaseRepository<T> repository

2023-07-27 15:03 UTC, JefersonPalomo commented on src/main/java/com/example/forge/models/entities/Teacher.java
> +
Conque se en la parte posterior de la clase ya es suficiente.

2023-07-27 16:23 UTC, MarcosAlanya19 requested changes

2023-07-27 16:23 UTC, MarcosAlanya19 commented on src/main/java/com/example/forge/controllers/TeacherController.java
> +	@GetMapping("/{id}")
Que solo este el {id} esa / está demas

2023-07-27 16:23 UTC, MarcosAlanya19 commented on src/main/java/com/example/forge/services/TeacherService.java
> +	public Teacher findById(Long id) {
El nombre debe de ser getById

2023-07-27 16:23 UTC, MarcosAlanya19 commented on src/main/java/com/example/forge/services/TeacherService.java
> +	public List<Teacher> findAll(){
El nombre debe de ser getAll

2023-07-27 16:41 UTC, merged